trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - src/*
      - azure-pipelines.yml
pr:
  branches:
    include:
      - "*"
pool:
  vmImage: "windows-latest"

variables:
- group: simplic-deployment
- group: simplic-deployment-dev01
- name: buildConfiguration
  value: "Release"

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: simplic/build-infrastructure
      endpoint: simplic-bot

steps:

  - checkout: self
    persistCredentials: true

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 5.x
  - task: NuGetCommand@2
    inputs:
      command: restore
      restoreSolution: "**/*.sln"
      feedsToUse: select
      vstsFeed: f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e
  - task: MSBuild@1
    inputs:
      solution: "**/*.sln"
      configuration: $(buildConfiguration)

  - ${{ if not(eq(variables['Build.Reason'], 'PullRequest')) }}:
      - template: version-number-update-token-template.yml@infrastructure
        parameters:
          connection_string: $(connection_string)
          git_user: $(git_user)
          git_token: $(git_token)
          branch_name: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}

  - task: NuGetCommand@2
    inputs:
      command: pack
      packagesToPack: src/Simplic.Navigation.Command**/*.csproj;!src/Simplic.Navigation.Command.Test/Simplic.Navigation.Command.Test.csproj
      configuration: $(buildConfiguration)
      versioningScheme: "off"
  - task: NuGetCommand@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      packagesToPush: $(Build.ArtifactStagingDirectory)/Simplic.Navigation.Command.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.Navigation.Command.*.symbols.nupkg
      nuGetFeedType: internal
      publishVstsFeed: f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e
      allowPackageConflicts: true
